project_name: shelltools
version: 2

before:
  hooks:
    - go get -u ./cmd/cmdforeach
    - go get -u ./cmd/cmdwithall
    - go get -u ./cmd/distinctline
    - go get -u ./cmd/jsonorderby
    - go get -u ./cmd/jsontotable
    - go get -u ./cmd/jsontransform
    - go get -u ./cmd/jsonwhere
    - go get -u ./cmd/linetojson
    - go mod tidy

builds:
  - id: cmdforeach
    binary: cmdforeach
    main: ./cmd/cmdforeach
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Tag}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: cmdwithall
    binary: cmdwithall
    main: ./cmd/cmdwithall
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Tag}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: distinctline
    binary: distinctline
    main: ./cmd/distinctline
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Tag}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: jsonorderby
    binary: jsonorderby
    main: ./cmd/jsonorderby
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: jsontotable
    binary: jsontotable
    main: ./cmd/jsontotable
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: jsontransform
    binary: jsontransform
    main: ./cmd/jsontransform
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: jsonwhere
    binary: jsonwhere
    main: ./cmd/jsonwhere
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: linetojson
    binary: linetojson
    main: ./cmd/linetojson
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

release:
  name_template: "Release {{.Tag}}"

changelog:
  use: github-native

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{- .Tag }}_{{ .Arch }}"
    maintainer: "https://github.com/dvaumoron"
    homepage: https://github.com/dvaumoron/shelltools
    description: >-
      Some CLI utilities to combine within shell (inspired by https://www.nushell.sh).
    license: "GPL-3.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: default
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/shelltools/copyright
        file_info:
          mode: 0444
    rpm:
      packager: tofuutils <tofuutils@gmail.com>
      signature:
        key_file: '{{ if index .Env "GPG_KEY_FILE" }}{{.Env.GPG_KEY_FILE}}{{ end }}'
    deb:
      signature:
        key_file: '{{ if index .Env "GPG_KEY_FILE" }}{{.Env.GPG_KEY_FILE}}{{ end }}'
    apk:
      signature:
        key_file: '{{ if index .Env "GPG_KEY_FILE" }}{{.Env.GPG_KEY_FILE}}{{ end }}'

brews:
  - repository:
      owner: dvaumoron
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/dvaumoron/shelltools
    description: Some CLI utilities to combine within shell (inspired by https://www.nushell.sh)
    license: "GPL-3.0"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
